version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/app/.bundle
    volumes:
      - .:/myapp
      - bundle_path:/bundle/vendor
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres:
  bundle_path: